### ISSUE TITLE
features in dev mergen

### ISSUE THREAD

**Issue by rctxs** [fub-agdb/cmsb#10]
## Features
* [X] library
* [X] mediafile
* [X] prescription_website
* [X] prescription
* [X] saml
* [X] gateway
* [x] labresult
* [x] patientrecord
* [x] swagger ui
* [ ] ~config-server~

**Comment by rctxs** [comment]
pull request für library wurde erstellt

**Comment by rctxs** [comment]
feature/mediafile ist gemerged

**Comment by rctxs** [comment]
feature/prescription_website ist gemerged

**Comment by rctxs** [comment]
#16 zuul-config ist im dev

**Comment by rctxs** [comment]
#15 prescription ist im dev

**Comment by rctxs** [comment]
#19 swagger ist im dev

**Comment by Nholan** [comment]
Config Server ist erstma zweitrangig und es gibt schon ein Issue dazu.
