### ISSUE TITLE
SAML login

### ISSUE THREAD

**Issue by rctxs** [fub-agdb/cmsb#11]

**Comment by rctxs** [comment]
Ich habe meinen Zwischenstand in feature/saml-test geschoben.

**Comment by rctxs** [comment]
SAML funktioniert. Jetzt möchte ich nur noch erreichen, dass URLs, welche keine Sicherheitsregeln haben, per default abgelehnt werden.

**Comment by rctxs** [comment]
Der Code ist jetzt fertig. #18

**Comment by groettrup** [comment]
Pull-Request für das feature wurde gemerged _(commit e714f2ab)_

---

@rctxs, vielleicht kannst du dir die stelle in #18 ansehen, die ich in meinem Review habe.
