### ISSUE TITLE
prescription Website MS

### ISSUE THREAD

**Issue by Will-i-am7** [fub-agdb/cmsb#12]

**Comment by ivncdrc** [comment]
Habe die Website als Micro Service implementiert. Ist im feature/prescription_website Branch vorhanden. Raphael testet es noch bei sich, ob es auch bei ihm funktioniert.

**Comment by rctxs** [comment]
Ich habe noch ein paar kleine Änderungen gemacht damit die Website sowohl lokal mit http also auch auf dem Server mit https funktioniert. Außerdem habe ich den Service noch in prescription-web-service umbenannt.
