### ISSUE TITLE
Präsentation SAML

### ISSUE THREAD

**Issue by groettrup** [fub-agdb/cmsb#21]
# Was wollen wir genau präsentieren?

Wichtig ist wahrscheinlich **SAML** und die **Beispielapp**.

**Comment by rctxs** [comment]
Wir sollten nochmal die Information weitergeben, dass die ZeDat Nutzernamen in der Datenbank eingetragen werden müssen, damit diese für das Testen der API Zugirff haben. Die Nutzernamen werden dann am Besten an uns weitergereicht, damit wir sie eintragen können.
