### ISSUE TITLE
Wiki Anleitung wie man das CMSB deployed/lokal ausführt

### ISSUE THREAD

**Issue by Nholan** [fub-agdb/cmsb#26]
- Step by Step Wiki Anleitung für alle Abhängigkeiten die man Installieren muss und konfigurationen die vorzunehmen sind um das CMSB lokal zu starten
- Step by Step Wiki Anleitung in der beschrieben wird wie man die Services für den live oder dev server deployed.

**Comment by rctxs** [comment]
I made a first draft. But I put it into the readme.md. That makes shure it is still available if the repo is moved to another place.
