### ISSUE TITLE
URL-Design

### ISSUE THREAD

**Issue by Will-i-am7** [fub-agdb/cmsb#6]

**Comment by rctxs** [comment]
Ich schlage folgende URL Struktur für die REST API vor:
- für die Tierklinik App: /swp/tierklinik/**
- für die Vetmed App (e-learning): /swp/vetmed/**
- für die Petcheck App: /swp/petcheck/**

**Comment by rctxs** [comment]
Desweiteren schlage ich folgende URL Struktur für die Websites vor:
- für den  E-Learning Webservice: /web/vetmed/**
- für die Administration: /web/admin/**
- für den Kyrotechnik Webservice: /web/kyrotechnik/**

**Comment by rctxs** [comment]
Die Konfiguration im gateway würde dann derzeit so aussehen:
- /swp/tierklinik/labresult/** --> patientrecord-service (weil der patientrecord-service auch die Anfragen für labresult übernehmen wird)
- /swp/tierklinik/emergencyDoc/** -> mediefile-service
- /swp/tierklinik/emergencyMp3/** -> mediefile-service
- /swp/tierklinik/pictures/** -> mediefile-service
- /swp/tierklinik/patientRecord/** -> patiendrecord-service
- /swp/tierklinik/prescription/** -> prescription-service
- /web/admin/** -> ?
- /web/kyrotechnik/** -> ?
- /web/tierklinik/** -> prescription-web-service
- /web/vetmed/** -> ?

**Comment by Nholan** [comment]
Ich würde mich hiermit auch gerne nochmal befassen aber frühestens erst am Mittwoch

**Comment by rctxs** [comment]
Ich habe meinen Vorschlag erstmal in #16 umgesetzt. Das kann natürlich noch angepasst werden.

**Comment by Nholan** [comment]
Wie ich schon bereits im Meeting erwähnt hatte, werden URLs für REST-APIs idR. so designed, dass sie eine Ressource aufrufen. Quasi wie ein Pfad zur einer Datei in einem Betriebssystem. Die URL aus dem production Server `patientrecord/animal?animalId={id}` sollte besser `patientrecord/animals/{animalId}` heißen. Was etwa bedeutet: Gebe mir aus dem Ordner "animals" das Tier mit der animalId={id}. Desweiteren werden Query-Parameter dazu verwendet die Ergebnisse zu Filtern. Also wenn man Tiere sucht die den Namen Bob haben dann sollte die URL wie folgt aussehen: `patientrecord/animals?animalName=Bob`. Im Production-Server würde das ebenfalls unter die URL `patientrecord/animal?animalName={name}` fallen. Der Name eines Tieres ist aber nicht eindeutig und aus /animal geht nicht heraus, dass jetzt eine Liste zurückgegeben wird. Im production Server wird sogar immer eine Liste zurückgegeben, auch wenn man mit der animalId sucht.

Aus Erfahrung weiß ich, dass dieses Schema nicht immer so einfach anzuwenden ist wie im gegebenen Beispiel, aber als prinzipielles Vorgehen würde ich vorschlagen sich daran zu halten und bei Problemen gemeinsam nach einer Lösung suchen.

Ich glaube Johannes hat sich im V2 daran gehalten, aber wir müssen ja auch neue URLs designen daher wollte ich das mal hier festhalten.

Es gibt noch ein paar mehr Best Practices die man beachten sollte die im folgenden Link sehr übersichtlich dargestellt sind:
https://restfulapi.net/resource-naming/

**Comment by rctxs** [comment]
Ich bin auch dafür, das wir diese Best Practieces soweit wie möglich umsetzen. Das klingt alles sehr logisch, wie es auf der Seite beschrieben ist. Die Frage ist nur, wie wir das jetzt praktisch machen können. Die Idee war ja, die alte API auf einem anderen Port zu belassen. Jetzt haben wir aber erfahren, dass wir mit SAML nur auf dem registrierten Port arbeiten können.

**Comment by rctxs** [comment]
Wenn wir eh die URLs aktualisieren, können wir wie besprchen, den `/swp`-Präfix entfernen.

**Comment by rctxs** [comment]
Wir könnten dann `/tierklinik` und `/e-learning` als neue Präfixe für die Tierklink-API respektive für die E-Learning-API verwenden. Den Präfix `/vetmed` wollte Nico nicht haben. Gibt es noch andere Vorschläge?

**Comment by braflo** [comment]
Ich glaube Nico wollte statt E-Learning, Skills Lab App.
Also sollten wir wsl mit /skillslabapp gehen.

**Comment by Nholan** [comment]
Ich möchte Veto gegen skillslabapp einlegen. Allerdings finde ich das lab ganz gut. Wie wärs stattdessen mit folgenden Vorschlägen:
/learninglab
oder wenn e learning mit dabei sein muss:
/elearninglab

**Comment by groettrup** [comment]
Ich habe mich gerade in der tierklinik_app mit der Patientenakte beschäftigt und bin da auf inkonsistente Pattern gestoßen. Das Kommentar soll mal aus der Sicht der App, vor allem der Suchfunktion, die Anforderungen beschreiben.

Die in der Suche zurückgegebenen Elemente treten nur in zwei Arten auf: _Patienten_ und _Owner_.
Für Owner gibt es nur Abfragen ohne genaue Id, weshalb hier Query Komponenten sinnvoll wären.

Bei Patienten gibt es zwar eine Id, wenn die aber nicht genutzt wird, muss eine Liste von Patienten zurückgegeben werden. Hier kann auch über den Owner gesucht werden.

* `/owners?`
  - `ownerFirstName={firstName}`
  - `ownerLastName={lastName}`
* `/patients/{patientId}`
* `/patients?`
  - `name={name}`
  - `case={case}` 
  - `ownerFirstName={firstName}`
  - `ownerLastName={lastName}`

Vorallem für die owner Cases wären _Custom Queries_ in den Repositories vielleicht angebracht.

--- 
## Hier noch einmal alle möglichen Eingabefelder der App
![screenshot_1536266233](https://user-images.githubusercontent.com/16621175/45184637-cf870080-b227-11e8-9392-36c2cf666359.png)

**Comment by rctxs** [comment]
Offensichtlich haben sich jetzt folgende Präfixe durchgesetzt:
- /swp/tierklink
- /web/tierklinik
- /vet/skillslab

Ich denke, wir können das bis aufs Weitere so belassen.
